a = input("what is the first number >>")
b = input("what is the second number >>")
c = input("what is the operator [+ - * /] >>")
print(eval(f"{a} {c} {b}"))
print("hello world")
print("I want to make a calculator")